config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "users#index"

  resources :users, only: [:index, :show] do
    resources :posts do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [ :create]
    end
  end

  namespace :api do
    resources :posts, only: [:index] do
      resources :comments, only: [:index, :create]
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:
    user ||= User.new # guest user (not logged in)

    return unless user.present?

    can :read, Post # start by defining rules for all users, also not logged ones
    can :manage, User, id: user.id # if the user is logged in can manage it's own profile
    can :manage, [Post, Comment], author_id: user.id
    can :create, Comment # logged in users can also create comments
    return unless user.is? :admin

    can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_create :save
  after_save :update_comment_counter

  after_destroy :update_comment_counter

  def update_comment_counter
    post.update(comments_counter: post.comments.count)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_create :save
  after_save :update_like_counter

  def update_like_counter
    post.update(likes_counter: post.likes.count)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments
  has_many :likes

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  after_create :save
  after_save :update_post_counter

  after_destroy :update_post_counter

  def update_post_counter
    author.update(posts_counter: author.posts.count)
  end

  def recent_comment
    comments.order(created_at: :asc).limit(5)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: :author_id
  has_many :comments, foreign_key: :author_id
  has_many :likes, foreign_key: :author_id

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  after_create :save

  ROLES = %i[admin default].freeze

  def is?(requested_role)
    role == requested_role.to_s
  end

  def recent_post
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/api/comments_controller.rb
class Api::CommentsController < ApplicationController
  def index
    @comments = Comment.includes(:author, :post).where(post_id: params[:post_id])
    render json: @comments
  end

  def create
    @comment = Comment.create(author_id: current_user.id, post_id: params['post_id'], text: params['text'])

    if @comment.save
      respond_to do |format|
        format.html { redirect_to user_post_path(params[:user_id], params[:post_id]), notice: 'Comment created.' }
        format.json { render json: @comment }
      end
    else
      respond_to do |format|
        format.html { redirect_to user_post_path(params[:user_id], params[:post_id]), notice: 'Comment not created.' }
        format.json { render json: @comment.errors }
      end
    end
  end
end

app/controllers/api/posts_controller.rb
class Api::PostsController < ApplicationController
  def index
    @posts = Post.all
    render json: @posts
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name email password])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.create(author_id: current_user.id, post_id: params['post_id'], text: params['text'])

    redirect_to user_post_path(params[:user_id], params[:post_id]) if @comment.save
  end

  def destroy
    @comment = Comment.find_by(id: params[:id])

    redirect_to user_post_path(params[:user_id], params[:post_id]) if @comment.destroy
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = Like.create(author_id: current_user.id, post_id: params[:post_id])

    redirect_to user_posts_path(params[:user_id]) if @like.save
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :users_check, :posts_list
  before_action :post_check, only: [:show]

  def index
    @posts = @posts.paginate(page: params[:page], per_page: 5)
  end

  def show; end

  def new
    @post = Post.new
  end

  def create
    @post = @user.posts.build(post_params)

    if @post.save
      redirect_to user_post_path(current_user, @post), notice: 'Post created successfully'
    else
      render html: 'Error'
    end
  end

  def destroy
    load_and_authorize_resource

    @post = @user.posts.find_by(id: params[:id])

    if @post.destroy
      redirect_to user_posts_path(current_user), notice: 'Post deleted successfully'
    else
      render html: 'Error'
    end
  end

  private

  def users_check
    @user = User.find_by(id: params[:user_id])
  end

  def posts_list
    @posts = @user.posts.includes(:author, comments: :author).order(created_at: :asc)
  end

  def post_check
    @post = @user.posts.includes(comments: :author).find_by(id: params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.includes(:posts, :comments, :likes).find_by(id: params[:id])

    return unless @user.nil?

    render html: 'User not found', status: :not_found
  end
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <p class="notice"><%= notice %></p>
  </body>
</html>

app/views/posts/index.html.erb
<main>

    <%if @posts.nil? || @posts.empty? %>
        <h1>There is no posts for this user</h1>
    <%else%>
        <%= render partial: 'shared/user_card', object: @user, as: :user %>

        <h1>Here is the list of posts</h1>
        
        <%@posts.each do |post|%>
        
            <%= link_to user_post_path(@user, post.id) do%>
                <%= render partial: 'shared/post_card', locals: {post: post, like: @like} %>
                <div class="comment-card">
                    <% post.recent_comment.each do |comment|%>
                        <%= render partial:'shared/comment_card', locals: {comment: comment, model: @comment, url: user_post_comment_path(@user, post, comment)} %>
                    <% end %>
                </div>
            <% end  %>
        <%end%>

        <%= link_to "Create a Post", new_user_post_path , class:'btn'%>

        <%= will_paginate @posts %>
    <% end%>

</main>

app/views/posts/new.html.erb
<main>
    <h1>New Post</h1>
    <%= form_with model:@post, url:user_posts_path do |f| %>
        <div class='form-control'>
            <%= f.label :title %>
            <%= f.text_field :title, placeholder: 'Title', required: true , class: 'input'%>
        </div>
        <div class='form-control'>
            <%= f.label :text, 'Content'%>
            <%= f.text_area :text, placeholder: 'Content', rows: 5, required: true , class: 'input'%>
        </div>
        <%= f.submit "Create Post" , class: 'submit-btn'%>
    <% end %>
</main>

app/views/posts/show.html.erb
<main>
    <%if @post.nil? || @posts.nil?%>
        <h1>There is no posts</h1>
    <%else%>
        <%= render partial:'shared/delete_button', locals: {model: @post, url: user_post_path(@user, @post)} %>
        <h2><cite><%= @post.title%></cite> by <%= @user.name%></h2>
        <p><%= @post.text%></p>
        <i class='count'>Comments: <%= @post.comments_counter%> </i> 

        <%= form_with model: @like, url: user_post_likes_path(@post.author_id, @post), method: :post, class: 'btn-container' do |f| %>
            <%= f.button type: :submit, class: 'count like-btn' do%>
                <%= @post.likes_counter%> Likes	&hearts;
            <% end %>  
        <% end%>
        
        <div class="comment-card">
            <% @post.comments.each do |comment|%>
                <%= render partial:'shared/comment_card', locals: {comment: comment, url: user_post_comment_path(@user, @post, comment)} %>
            <% end %>
        </div>

        <%= render partial: 'shared/form_comment'%>
    <% end%>
</main>

app/views/shared/_comment_card.html.erb
<div class='comment-container'>
    <p><strong><%= comment.author.name %>:</strong><q><%= comment.text %></q></p>
    <%= render partial: 'shared/delete_button', locals: {model: comment, url: url}%>
</div>

app/views/shared/_delete_button.html.erb
<% if can? :destroy, model%>
    <%= button_to "Delete", url, method: :delete,  class: 'delete-btn'%>
<%end %>

app/views/shared/_form_comment.html.erb
<%= form_with model:@comment, url:user_post_comments_path(@user.id, @post.id) do |f| %>
    <h3>Leave a comment</h3>
    <%= f.text_area :text, placeholder: 'Context', rows: 2,  required: true, class:'input' %>
    <%= f.submit "Submit", class:'submit-btn' %>
<% end %>

app/views/shared/_header.html.erb
<header>
    <div class='left-group'>
        <div class="img-container">
            <img src=<%= current_user.photo %> id=<%= current_user.name%> alt=<%= current_user.name%>/>
        </div>
        <p><%= current_user.name %></p>
    <div>
</header>

app/views/shared/_post_card.html.erb
<div class='post' id="post-card-<%=post.id%>">
    <h2><cite><%= post.title%></cite> #<%= post.id%></h2>
    <p><%= post.text.slice(0,150).concat(' ...')%></p>
    <i class='count'>Comments: <%= post.comments_counter%></i>

    <%= form_with model: like, url: user_post_likes_path(post.author_id, post), method: :post, class: 'btn-container' do |f| %>
        <%= f.button type: :submit, class: 'count like-btn' do%>
            <%= post.likes_counter%> Likes 	&hearts;
        <% end %>  
    <% end%>

    <%= link_to 'Add Comment', user_post_path(post.author_id, post) %>
</div>

app/views/shared/_user_card.html.erb
<div class="user-card">
    <div class="img-container">
        <img src=<%= user.photo %> id=<%= user.name%> alt=<%= user.name%>/>
    </div>
    <div class="name-container">
        <h2 class='user-name'><%= user.name%></h2>
        <i class="count">Number of posts: <%= user.posts_counter%> </i>
    </div>
</div>

app/views/users/index.html.erb
<%= render partial:'shared/header'%>
<main>
    <h1>List of Users</h1>
    <% @users.each do |user|%>
        <%= link_to "/users/#{user.id}" do%>
            <%= render partial: 'shared/user_card', object: user, as: :user%>
        <% end %>
    <% end %>
</main>

app/views/users/show.html.erb
<main>
    <%= render partial: 'shared/user_card', locals: {user: @user}%>
    <article>
        <p>Bio: <%= @user.bio %></p>
    </article>
    <% @user.recent_post.each do |post|%>
        <%= link_to "/users/#{@user.id}/posts/#{post.id}" do%>
            <%= render partial: 'shared/post_card', locals: {post: post, like: @like}%>
            <div class="comment-card">
                <% post.recent_comment.each do |comment|%>
                <%= render partial:'shared/comment_card', locals: {comment: comment, url: user_post_comment_path(@user, post, comment)} %>
                <% end %>
            </div>
        <% end%>
    <% end %>

    <%= link_to 'See All Posts', user_posts_path(@user), class: 'btn'%>
</main>